/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "TIMER.h"
#include "UART_1.h"
#include "ROW0_aliases.h"
#include "ROW0.h"
#include "ROW3_aliases.h"
#include "ROW3.h"
#include "ROW2_aliases.h"
#include "ROW2.h"
#include "ROW1_aliases.h"
#include "ROW1.h"
#include "COL1_aliases.h"
#include "COL1.h"
#include "COL3_aliases.h"
#include "COL3.h"
#include "COL2_aliases.h"
#include "COL2.h"
#include "PWM_GAUCHE.h"
#include "PWM_DROITE.h"
#include "timer_clock_1.h"
#include "timer_clock_2.h"
#include "VDAC.h"
#include "AUDIO_aliases.h"
#include "AUDIO.h"
#include "LED_1_aliases.h"
#include "LED_1.h"
#include "LED_2_aliases.h"
#include "LED_2.h"
#include "LED_3_aliases.h"
#include "LED_3.h"
#include "LED_4_aliases.h"
#include "LED_4.h"
#include "SWITCH_1_aliases.h"
#include "SWITCH_1.h"
#include "SWITCH_2_aliases.h"
#include "SWITCH_2.h"
#include "SWITCH_3_aliases.h"
#include "SWITCH_3.h"
#include "SWITCH_4_aliases.h"
#include "SWITCH_4.h"
#include "ADC_POTENTIOMETRE.h"
#include "PIN_POTENTIOMETER_aliases.h"
#include "PIN_POTENTIOMETER.h"
#include "LCD_Char_1.h"
#include "UART_1_IntClock.h"
#include "ADC_POTENTIOMETRE_AMux.h"
#include "ADC_POTENTIOMETRE_Ext_CP_Clk.h"
#include "ADC_POTENTIOMETRE_IRQ.h"
#include "ADC_POTENTIOMETRE_theACLK.h"
#include "LCD_Char_1_LCDPort_aliases.h"
#include "LCD_Char_1_LCDPort.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

